<a href="https://colab.research.google.com/github/ggpp200/corap/blob/master/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C!!.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [1]:
import numpy as np

In [2]:

import pandas as pd
pd.__version__
# 버전확인

'1.1.5'

## Pandas 객체


### Series 객체

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s
# 시리즈는 한줄짜리 데이터 집합

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [ ]:
s.values
# 값만 볼때 사용

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.index
# 인덱스 범위 출력, 현재는 range로 0~4까지 표현

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s[1]
# 인덱스로 접근

0.25

In [ ]:
s[1:4]
# 슬라이싱도 가능

1    0.25
2    0.50
3    0.75
dtype: float64

In [ ]:
s = pd.Series([0.  , 0.25, 0.5 , 0.75, 1.0], index = ['a', 'b', 'c', 'd', 'e'])
s
# 인덱스 지정 가능

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
'b' in s
# 파이선의 in 함수 사용가능

True

In [ ]:
s =pd.Series([0.  , 0.25, 0.5 , 0.75, 1.0], index = ['2', '4', '6', '8', '10'])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s.unique()
# 유니크한 값만 출력


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.value_counts()
# 각 밸류 갯수 세기

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [ ]:
s.isin([0.25, 0.75])
# 특정 숫자가 안에 있는게 확인되면 True

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [ ]:
pop_dict = {'서울특별시' : 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 147105,
            '광주광역시': 1455048}
population = pd.Series(pop_dict)
population
# 정보를 dictionary로 만들기

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시     147105
광주광역시    1455048
dtype: int64

In [ ]:
population['서울특별시']
# 인덱싱

9720846

In [ ]:
population['서울특별시': '인천광역시']
# 인덱싱2

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

데이터 프레임은 2차원 배열이라고 생각하면 됨


In [ ]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])
# 데이터프레임 예제(이때, 각 C와 D에 누락값 NaN으로 표기)

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [ ]:
pd.DataFrame(np.random.rand(5, 5), columns = ['A', 'B', 'C', 'D', 'E'], index = [1, 2, 3, 4, 5])
# colums와 index 수정

A         B         C         D         E
1  0.016289  0.699505  0.292811  0.351839  0.172492
2  0.407431  0.452060  0.384654  0.577077  0.667360
3  0.592701  0.309823  0.300841  0.531807  0.480388
4  0.325518  0.494185  0.037097  0.102736  0.826584
5  0.987850  0.791069  0.936665  0.438043  0.849716

In [ ]:
male_dict = {'서울특별시' : 4732275,
            '부산광역시': 1668618,
            '인천광역시': 1476813,
            '대구광역시': 1198815,
            '대전광역시': 734441,
            '광주광역시': 720060}
male = pd.Series(male_dict)
male
# 남자 인구수 정의 및 출력

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [ ]:
female_dict = {'서울특별시' : 4988571,
            '부산광역시': 1735805,
            '인천광역시': 1470404,
            '대구광역시': 1229139,
            '대전광역시': 736599,
            '광주광역시': 734988}
female = pd.Series(female_dict)
female
# 여자 인구수 정의 및 출력

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [ ]:
korea_df = pd.DataFrame({'인구수':population,
                        '남자인구수':male,
                        '여자인구수': female})
korea_df
# 3개의 Series 를 DataFrame으로 나타내기

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시   147105   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df.index
# 인덱스 내역 보기

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [ ]:
korea_df.columns
# columns 내역보기

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [ ]:
korea_df['서울특별시':'인천광역시']
#df슬라이싱

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체



Index           일반적인 index로 Numpy 배열의 축

int64index      정수 값을 위한 index

Multiindex      단일 축에 여러 단계 색인을 표현하는 계층적 idnex 객체

Datetimeindex   Numpy의 datetime64 타입으로 타임스탬프 저장

Periodindex     기간 데이터를 위한 index



In [ ]:
idx = pd.Index([2,4,6,8,10])
idx
# 인덱스 Series객체 생성

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [ ]:
idx[1:2:2]
#슬라이싱 연습1

Int64Index([4], dtype='int64')

In [ ]:
idx[::-1]
# 슬라이싱(역)

Int64Index([10, 8, 6, 4, 2], dtype='int64')

In [ ]:
idx[-1::]
#슬라이싱 연습(마지막 글자)

Int64Index([10], dtype='int64')

In [ ]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [ ]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)
# 인덱스 출력
# 인덱스 사이즈
# 인덱스 1차원 shape
# ndim은 배열의 차수이므로 1차원 이므로 1
# 데이터 타입 인트

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

append                색인 객체를 추가한 새로운 색인 반환

difference            색인의 차집합 반환

intersection          색인의 교집합 반환

union                 색인의 합집합 반환(중복 삭제)


isin                  색인이 존재하는지 여부를 불리언 배열로 반환

delete                색인이 삭제된 새로운 색인 반환

drop                  값이 삭제된 새로운 색인 반환

insert                색인이 추가된 새로운 색인 반환

is_monotonic          색인이 단조성을 가지면 True

is_unique             중복되는 색인이 없다면 True

unique                색인에서 중복되는 요소를 제거하고 유일한 값만 반환


In [ ]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])




In [ ]:
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
# 추가, 차집합, 차집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')


In [ ]:
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx.union(idx2))
# 교집합, 교집합, 합집합

Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 5, 6, 7, 8, 10], dtype='int64')


In [ ]:
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2)
# 합집합, 삭제, 삭제, 여집합

Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['b']

0.25

In [ ]:
'b' in s

True

In [ ]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [ ]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [ ]:
s['a':'d']


a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [ ]:
s[['a', 'c', 'e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [ ]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'], index = [1, 3, 5, 7, 9])

In [ ]:
s[1]
# 직접 지정한 인덱스사용

'a'

In [ ]:
s[2:4]

5    c
7    d
dtype: object

In [ ]:
s.iloc[1]
# 직접 지정한 인덱스 말고 원래 숫자인 정수값으로 접근

'b'

In [ ]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [ ]:
s.reindex(range(10))
# reindex는 새로운 인덱스 구축, 이때 없는 값은 NaN 표기됨

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [ ]:
s.reindex(range(10), method = 'bfill')
# bfill은 before fill로 전값으로 채움

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


df[val] 하나의 컬럼 또는 여러 컬럼 선택

df.loc[val] 라벨값으로 로우의 부분집합 선택

df.loc[:,val] 라벨값으로 컬럼의 부분집합 선택

df.loc[val1,val2] 라벨값으로 로우와 컬럼의 부분집합 선택

df.iloc[where] 정수색인으로 로우의 부분집합 선택

df.iloc[:,where] 정수색인으로 컬럼의 부분집합 선택

df.iloc[where_i, where_j] 정수 색인으로 로우와 컬럼의 부분집합 선택

df.at[label_i, label_j] 로우와 컬럼의 라벨로 단일 값 선택

df.iat[i,j] 로우와 컬럼의 정수 색인으로 단일 값 선택

reindex 하나 이상의 축을 새로운 색인으로 재색인

get_value, set_value 로우와 칼럼의 이름으로 값 선택

In [ ]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df.남여비율 = korea_df.남자인구수 * 100 / korea_df.여자인구수

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


In [ ]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
dtype: float64

In [ ]:
korea_df.values

array([[9720846, 4732275, 4988571],
       [3404423, 1668618, 1735805],
       [2947217, 1476813, 1470404],
       [2427954, 1198815, 1229139],
       [ 147105,  734441,  736599],
       [1455048,  720060,  734988]])

In [ ]:
korea_df.T
# 표로 나타내기 

서울특별시    부산광역시    인천광역시    대구광역시   대전광역시    광주광역시
인구수    9720846  3404423  2947217  2427954  147105  1455048
남자인구수  4732275  1668618  1476813  1198815  734441   720060
여자인구수  4988571  1735805  1470404  1229139  736599   734988

In [ ]:
korea_df.values[0]
# 한줄만 보기

array([9720846, 4732275, 4988571])

In [ ]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시     147105
광주광역시    1455048
Name: 인구수, dtype: int64

In [ ]:
korea_df.loc[:'인천광역시', :'남자인구수']
# 각 행과 열에대해 인덱싱

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [ ]:
korea_df.loc[(korea_df.여자인구수 >1000000)]
# 조건에 따라 인덱싱

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139

In [ ]:
korea_df.loc[(korea_df.인구수 < 200000)]

인구수   남자인구수   여자인구수
대전광역시  147105  734441  736599

In [ ]:
korea_df.loc[(korea_df.인구수 > 25000000) & (korea_df.남여비율 > 100)] 
# 2가지 조건문 이용

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수]
Index: []

In [ ]:
korea_df.iloc[:3,:2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [ ]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시   147105   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020),
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [ ]:
pop_tuples = [10312545, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)
population
# 직접 시리즈 이어붙여서 3차원 배열 만들기

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [ ]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx
# 멀티인덱스 이용해서 만들기

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [ ]:
population = population.reindex(midx)
population
#위의 코드 + reindex

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [ ]:
korea_mdf = population.unstack()
# 다중인덱싱 시리즈들을 데이터 프레임으로 변환하는게 unstack
korea_mdf


2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
korea_mdf.stack()
# 다시 다중인덱스 사용 stack

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

#### 다중 인덱스 생성

In [ ]:
df = pd.DataFrame(np.random.rand(6,3),
                  index=[['a','a','b','b','c','c'], [1,2,31,2,1,2]],columns=['c1','c2','c3'])
df
# 멀티인덱스 바로생성

c1        c2        c3
a 1   0.599082  0.208699  0.265229
  2   0.119025  0.147006  0.984719
b 31  0.806218  0.243589  0.434286
  2   0.438189  0.458100  0.243591
c 1   0.703139  0.069691  0.881562
  2   0.751839  0.809119  0.047811

In [ ]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1,2,1,2,1,2]])
# arrays 로 2차원만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c',2)])
# 모양만들기 튜플로 2차원만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])
# 프로덕트로 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels = [['a', 'b', 'c'], [1, 2]], codes = [[0, 0, 1, 1, 2, 2],[0, 1, 0, 1, 0, 1]])
# level * codes로 멀티인덱스 만들기

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population.index.names = ['행정구역', '년도']
population
# 인덱스 이름 붙이기

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]], names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]], names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index = idx, columns = cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.89 -0.73 -1.66  0.03  1.18 -0.21
      2      0.52 -0.16 -0.23 -0.29 -1.45  1.42
b     1      0.16  1.05 -1.71  0.63 -0.88  0.07
      2      0.61 -1.81  0.28  0.09  0.30  2.92
c     1      0.50  0.92 -0.41 -1.93 -2.34 -1.45
      2     -1.14  0.35 -1.08 -0.88 -0.11 -0.59

In [ ]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -1.66  0.03
      2     -0.23 -0.29
b     1     -1.71  0.63
      2      0.28  0.09
c     1     -0.41 -1.93
      2     -1.08 -0.88

#### 인덱싱 및 슬라이싱

In [ ]:
population['인천광역시',  2010]

2758296

In [ ]:
population[:,2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [ ]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [ ]:
mdf['c2', 1]

name1  name2
a      1       -1.66
       2       -0.23
b      1       -1.71
       2        0.28
c      1       -0.41
       2       -1.08
Name: (c2, 1), dtype: float64

In [ ]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.89 -0.73 -1.66  0.03
      2      0.52 -0.16 -0.23 -0.29
b     1      0.16  1.05 -1.71  0.63

In [ ]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -1.66
       2       -0.23
b      1       -1.71
       2        0.28
c      1       -0.41
       2       -1.08
Name: (c2, 1), dtype: float64

In [ ]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:,2], idx_slice[:,2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.16 -0.29  1.42
b     2     -1.81  0.09  2.92
c     2      0.35 -0.88 -0.59

#### 다중 인덱스 재정렬

In [ ]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [ ]:
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
korea_mdf['서울특별시' : '인천광역시']

2010     2020
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
다차원 인덱싱은 나중에 할래!

## 데이터 연산

In [ ]:
s = pd.Series(np.random.randint(0, 10, 5))
s
# s라는 랜덤 시리즈 만들기

0    5
1    2
2    8
3    6
4    0
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0,10, (3, 3)), columns = ['A', 'B','C'])
df

A  B  C
0  9  7  9
1  9  8  0
2  2  7  0

In [ ]:
np.exp(s)
# exp 사용 지수함수 e^s

0     148.413159
1       7.389056
2    2980.957987
3     403.428793
4       1.000000
dtype: float64

In [ ]:
np.cos(df * np.pi / 4)
# cos 사용

A         B         C
0  7.071068e-01  0.707107  0.707107
1  7.071068e-01  1.000000  1.000000
2  6.123234e-17  0.707107  1.000000

In [ ]:
s1 = pd.Series([1,3,5,7,9], index = [0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10], index = [1,2,3,4,5])
s1 +s2
# 빈공간이랑 더하면 NaN으로 표현

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value= 0)
# fill_value는 빈칸 디폴트로 더함

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)), columns = list('ACD'))
df1
# 0에서 20 가지중에 3,3개뽑기, 인덱스 = 지정 x, columns = 리스트 ACD

A   C  D
0   4   7  9
1  12  14  7
2   0  15  2

In [ ]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)), columns = list('BAECD'))
df2

B   A   E  C   D
0  14  16   9  7  17
1   4   7   3  7   4
2   8  14  17  7   7
3   2   8  16  1   9
4   4  19  15  8   7

In [ ]:
df1 + df2 
# 더하면 행정렬 되면서 빈칸 비움 이때 한쪽이라도 비어있으면 NaN

A   B     C     D   E
0  20.0 NaN  14.0  26.0 NaN
1  19.0 NaN  21.0  11.0 NaN
2  14.0 NaN  22.0   9.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value =fvalue)
# df1 + df2를 하면서 stack(위에서 아래로  채움 언스택은 왼쪽에서 오른쪽)

A          B          C          D          E
0  20.000000  21.777778  14.000000  26.000000  16.777778
1  19.000000  11.777778  21.000000  11.000000  10.777778
2  14.000000  15.777778  22.000000   9.000000  24.777778
3  15.777778   9.777778   8.777778  16.777778  23.777778
4  26.777778  11.777778  15.777778  14.777778  22.777778

### 연산자 범용 함수


#### add()

In [8]:
a = np.random.randint(1, 10, size = (3,3))
a

array([[7, 6, 5],
       [7, 9, 4],
       [1, 5, 1]])

In [9]:
a + a[0]

array([[14, 12, 10],
       [14, 15,  9],
       [ 8, 11,  6]])

In [10]:
df = pd.DataFrame(a, columns  = list('ABC'))
df

A  B  C
0  7  6  5
1  7  9  4
2  1  5  1

In [ ]:
df + df.iloc[0]

A   B   C
0   4  16  18
1  11  16  14
2   8   9  10

In [ ]:
df.add(df.iloc[0])

A   B   C
0   4  16  18
1  11  16  14
2   8   9  10

#### sub() / subtract()

In [ ]:
a

array([[2, 8, 9],
       [9, 8, 5],
       [6, 1, 1]])

In [ ]:
a - a[0]

array([[ 0,  0,  0],
       [ 7,  0, -4],
       [ 4, -7, -8]])

In [4]:
df

NameError: ignored

In [ ]:
df -  df.iloc[0]

A  B  C
0  0  0  0
1  7  0 -4
2  4 -7 -8

In [ ]:
df.subtract(df['B'], axis=0)
# subtract는 한 축을 기준으로 나머지의 상대치를 결정

A  B  C
0 -6  0  1
1  1  0 -3
2  5  0  0

#### mul() / multply()




In [ ]:
a

array([[2, 8, 9],
       [9, 8, 5],
       [6, 1, 1]])

In [ ]:
df

A  B  C
0  2  8  9
1  9  8  5
2  6  1  1

In [ ]:
a * a[1]

array([[18, 64, 45],
       [81, 64, 25],
       [54,  8,  5]])

In [ ]:
df.mul(df.iloc[1])

A   B   C
0  18  64  45
1  81  64  25
2  54   8   5

In [ ]:
df.multiply(df.iloc[2])

A  B  C
0  12  8  9
1  54  8  5
2  36  1  1

#### truediv() /  div() / divide() / floordiv()

In [ ]:
a

array([[2, 8, 9],
       [9, 8, 5],
       [6, 1, 1]])

In [ ]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [4.5       , 1.        , 0.55555556],
       [3.        , 0.125     , 0.11111111]])

In [ ]:
df

A  B  C
0  2  8  9
1  9  8  5
2  6  1  1

In [ ]:
df / df.iloc[0]

A      B         C
0  1.0  1.000  1.000000
1  4.5  1.000  0.555556
2  3.0  0.125  0.111111

In [11]:
df.truediv(df.iloc[0])
# 나누기


A         B    C
0  1.000000  1.000000  1.0
1  1.000000  1.500000  0.8
2  0.142857  0.833333  0.2

In [13]:
df.div(df.iloc[0])
# 나누기

A         B    C
0  1.000000  1.000000  1.0
1  1.000000  1.500000  0.8
2  0.142857  0.833333  0.2

In [16]:
df.divide(df.iloc[0])

A         B    C
0  1.000000  1.000000  1.0
1  1.000000  1.500000  0.8
2  0.142857  0.833333  0.2

In [17]:
a // a[0]

array([[1, 1, 1],
       [1, 1, 0],
       [0, 0, 0]])

#### mod()

In [18]:
a % a[0]
# 나머지

array([[0, 0, 0],
       [0, 3, 4],
       [1, 5, 1]])

In [19]:
df

A  B  C
0  7  6  5
1  7  9  4
2  1  5  1

In [23]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  0  3  4
2  1  5  1

#### pow()

In [24]:
a ** a[0]
# 제곱

array([[823543,  46656,   3125],
       [823543, 531441,   1024],
       [     1,  15625,      1]])

In [25]:
df.pow(df.iloc[0])

A       B     C
0  823543   46656  3125
1  823543  531441  1024
2       1   15625     1

In [27]:
row = df.iloc[0, ::2]
row

A    7
C    5
Name: 0, dtype: int64

In [28]:
df - row

A   B    C
0  0.0 NaN  0.0
1  0.0 NaN -1.0
2 -6.0 NaN -4.0

### 정렬(Sort)

In [30]:
s = pd.Series(range(5), index = ['A','D', 'C', 'B', 'E'])
s

A    0
D    1
C    2
B    3
E    4
dtype: int64

In [31]:
s.sort_index()

A    0
B    3
C    2
D    1
E    4
dtype: int64

In [32]:
s.sort_values()

A    0
D    1
C    2
B    3
E    4
dtype: int64

In [34]:
df = pd.DataFrame(np.random.randint*0, 10,(4, 4)), index = [2, 4, 1, 3], columns = list('BDAC'))

SyntaxError: ignored

### 순위(Ranking)


### 고성능 연산

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly